import { AppProps } from 'next/dist/shared/lib/router/router';
import React from 'react';
import Head from 'next/head';
import '../styles/globals.css';

function MyApp({ Component, pageProps, router }: AppProps): JSX.Element {
	return (
		<>
			<Head>
				<title>TopCourses | Лучшие курсы</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Display:wght@300;400;500;700&display=swap" rel="stylesheet" />
				<meta property="og:url" content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
				<meta property="og:locale" content="ru_RU" />
			</Head>
			<Component {...pageProps} />
		</>
	);
}

export default MyApp;
